### ISSUE TITLE
panda.get_system_memory() does not work

### ISSUE THREAD

**Issue by IridiumXOR** [panda-re/panda#1246]
If I try ```panda.get_system_memory()``` I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pandare/panda.py", line 1618, in get_system_memory
    return self.libpanda.get_system_memory()
AttributeError: cffi library '/usr/local/lib/python3.8/dist-packages/pandare/data/x86_64-softmmu/libpanda-x86_64.so' has no function, constant or global variable named 'get_system_memory'
```
however ```libpanda-x86_64.so``` has ```get_system_memory()``` exported as symbol...

**Comment by lacraig2** [comment]
Good catch. Seems as though CFFI doesn't have that symbol exported.

**Comment by IridiumXOR** [comment]
Please can someone  fix it or explain me how to do? I'm stucked...
