### ISSUE TITLE
[CI] Generic pypanda tests broken but reporting passing

### ISSUE THREAD

**Issue by AndrewFasano** [panda-re/panda#1356]
It seems that `generic_tests.py` as run by our CI is failing, but the tests are reported as passing. From https://github.com/panda-re/panda/actions/runs/6148260094/job/16689846816?pr=1352 we can see it downloads some stuff and then prints:

```
2023-09-11T19:34:53.1213921Z 2980750K .......... .......... .......... .......... ..........100% 17.4M 0s
2023-09-11T19:34:53.1214592Z 2980800K                                                       100% 0.00 =30stimeout: failed to run command ‘panda-system-x86_64’: No such file or directory
2023-09-11T19:34:53.1214700Z /bin/sh: 1: nc: not found
2023-09-11T19:34:53.1214815Z Traceback (most recent call last):
2023-09-11T19:34:53.1214988Z   File "./generic_tests.py", line 138, in <module>
2023-09-11T19:34:53.1215074Z     runner(argv[1])
2023-09-11T19:34:53.1215202Z   File "./generic_tests.py", line 73, in runner
2023-09-11T19:34:53.1215342Z     raise RuntimeError("Failed to run CLI panda")
2023-09-11T19:34:53.1215463Z RuntimeError: Failed to run CLI panda
2023-09-11T19:34:53.1215473Z 
2023-09-11T19:34:53.1215569Z Testing generic=x86_64...
2023-09-11T19:34:53.1215663Z [skipping duplicate]
2023-09-11T19:34:53.1215744Z Testing generic=i386...
2023-09-11T19:34:53.1215832Z [skipping duplicate]
2023-09-11T19:34:53.1215922Z Testing generic=ppc...
2023-09-11T19:34:53.1216009Z [skipping duplicate]
2023-09-11T19:34:53.1216097Z Testing generic=arm...
2023-09-11T19:34:53.1216183Z [skipping duplicate]
2023-09-11T19:34:53.1216280Z Testing generic=aarch64...
2023-09-11T19:34:53.1216395Z [skipping duplicate]
2023-09-11T19:34:53.1216486Z Testing generic=mips...
2023-09-11T19:34:53.1216574Z [skipping duplicate]
2023-09-11T19:34:53.1216670Z Testing generic=mipsel...
2023-09-11T19:34:53.1216753Z [skipping duplicate]
2023-09-11T19:34:53.1216831Z i386_wheezy FAIL
2023-09-11T19:34:53.1216911Z x86_64_wheezy FAIL
2023-09-11T19:34:53.1216984Z ppc_wheezy FAIL
2023-09-11T19:34:53.1217093Z arm_wheezy FAIL
2023-09-11T19:34:53.1217177Z aarch64_focal FAIL
2023-09-11T19:34:53.1217255Z mips64 FAIL
2023-09-11T19:34:53.1217337Z mips_wheezy FAIL
2023-09-11T19:34:53.1217418Z mipsel_wheezy FAIL
2023-09-11T19:34:53.1217494Z mips_buildroot5 FAIL
2023-09-11T19:34:53.1217585Z mipsel_buildroot5 FAIL
2023-09-11T19:34:53.1217668Z i386_ubuntu_1604 FAIL
2023-09-11T19:34:53.1217750Z x86_64_ubuntu_1804 FAIL
2023-09-11T19:34:54.1677926Z Cleaning up orphan processes
```

**Comment by lacraig2** [comment]
It appears to fail in the first part of the test of CLI panda: https://github.com/panda-re/panda/blob/dev/panda/python/tests/generic_tests.py#L66

I suspect that it could have something to do with it claiming that it's missing both `nc` and `panda-system-X`
```
failed to run command ‘panda-system-x86_64’: No such file or directory
/bin/sh: 1: nc: not found
```
