### ISSUE TITLE
Error while running python/examples/bbc_www.py because snapshot 'root' is not presented.

### ISSUE THREAD

**Issue by Kingsdom005** [panda-re/panda#1444]
Error information:

Traceback (most recent call last):
  File "/home/liyanqi/Desktop/PANDA/panda2/panda/panda/python/examples/bbc_www.py", line 40, in <module>
    panda.run()
  File "/home/liyanqi/Desktop/PANDA/.venv/lib/python3.8/site-packages/pandare/panda.py", line 548, in run
    raise saved_exception
  File "/home/liyanqi/Desktop/PANDA/.venv/lib/python3.8/site-packages/pandare/panda.py", line 950, in wrapper
    f()
  File "/home/liyanqi/Desktop/PANDA/.venv/lib/python3.8/site-packages/pandare/utils.py", line 92, in wrapper
    return func(*args, **kwargs)
  File "/home/liyanqi/Desktop/PANDA/panda2/panda/panda/python/examples/bbc_www.py", line 32, in driver
    panda.revert_sync("root")
  File "/home/liyanqi/Desktop/PANDA/.venv/lib/python3.8/site-packages/pandare/utils.py", line 92, in wrapper
    return func(*args, **kwargs)
  File "/home/liyanqi/Desktop/PANDA/.venv/lib/python3.8/site-packages/pandare/panda.py", line 2354, in revert_sync
    raise ValueError(f"Snapshot '{snapshot_name}' not present in {self.qcow}")
ValueError: Snapshot 'root' not present in /home/liyanqi/.panda/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2

Should I edit the file "bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2"?
How to solve the problem?

**Comment by AndrewFasano** [comment]
Did you delete the root snapshot? It's in there by default.
