### ISSUE TITLE
The recording of login/logout failed to replay, on the latest version of Win7 64-bit.

### ISSUE THREAD

**Issue by Dazdin9o** [panda-re/panda#396]
I found a case that PANDA cannot replay the process of login/logout on the lated version of Win7 64-bit.

It may caused by rr_memory_region_find_parent(), in panda/src/rr/rr_log.c:1013, returns NULL. Stack backtrace:

```
(gdb) bt
#0  0x0000555555a5052f in memory_region_del_subregion (mr=0x0, subregion=0x555557788170) at /home/jungu/timeplayer/timeplayer-src/memory.c:2091
#1  0x00005555559c47cb in rr_replay_skipped_calls_internal (call_site=<optimized out>) at /home/jungu/timeplayer/timeplayer-src/panda/src/rr/rr_log.c:1017
#2  0x00005555559fc4d4 in rr_replay_skipped_calls () at /home/jungu/timeplayer/timeplayer-src/panda/include/panda/rr/rr_log_all.h:331
#3  address_space_stw_internal (endian=DEVICE_NATIVE_ENDIAN, result=0x0, attrs=..., val=256, addr=<optimized out>, as=<optimized out>) at /home/jungu/timeplayer/timeplayer-src/memory_ldst.inc.c:585
#4  address_space_stw (as=<optimized out>, addr=<optimized out>, val=256, attrs=..., result=result@entry=0x0) at /home/jungu/timeplayer/timeplayer-src/memory_ldst.inc.c:620
#5  0x0000555555b1d521 in helper_outw (env=<optimized out>, port=<optimized out>, data=<optimized out>) at /home/jungu/timeplayer/timeplayer-src/target/i386/misc_helper.c:61
#6  0x00007fffd02ac6c9 in ?? ()
#7  0xfffff96000296000 in ?? ()
#8  0x000055555771b070 in ?? ()
#9  0x0000000000000005 in ?? ()
#10 0x0000555557723310 in ?? ()
#11 0x0000555558fe7620 in ?? ()
#12 0x00007ffff313b559 in g_hash_table_lookup () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x0000555555a06c77 in tcg_gen_callN (s=0x5555571f1060 <tcg_ctx>, func=0x555555b19040 <helper_cc_compute_c>, ret=4, nargs=4, args=0x7fffbade95d0) at /home/jungu/timeplayer/timeplayer-src/tcg/tcg.c:739
#14 0x00005555559efd73 in address_space_lookup_region (d=0x7fffbade9640, addr=0, resolve_subpage=<optimized out>) at /home/jungu/timeplayer/timeplayer-src/exec.c:405
#15 0x0000000000000005 in ?? ()
#16 0x0000555557723310 in ?? ()
#17 0xa98e965904bd7400 in ?? ()
#18 0xffffffffbade96f8 in ?? ()
#19 0x00007ffff313b559 in g_hash_table_lookup () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0xa98e965904bd7400 in ?? ()
#21 0x00007fff280008f8 in ?? ()
#22 0x00007fffbade9810 in ?? ()
#23 0xfffff88002aa7362 in ?? ()
#24 0xa98e965904bd7400 in ?? ()
#25 0x0000000000000000 in ?? ()
```

But limited by my understanding of PANDA, I cannot find the route cause :(

**Comment by moyix** [comment]
Assuming your PR (https://github.com/panda-re/panda/commit/e109e52bc946ca1c3675309ba6ec294c50815a51) fixed this, I'll close.
