### ISSUE TITLE
hanged on uninit_plugin

### ISSUE THREAD

**Issue by bingosxs** [panda-re/panda#846]
Hi,
 I'm experimenting with panda-re using the taint2 plugin. 

`/build/x86_64-softmmu/panda-system-x86_64  -m 512 -replay ../tracefiles64/tracefile -panda osi  -panda osi_linux:kconf_group=my_kernelinfo -panda syscalls2 -os linux-64-ubuntu:4.4.0-21-generic -panda ida_taint2 -panda file_taint:filename=crash,verbose=false,pos=false`

It hanged for a long time with a hot cpu and cannot exit normally.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                    
3501282 user  20   0 4763884   3.6g  59660 S  99.3   1.9 131:48.55 panda-system-x8        
```                                                                                                                                                                                    

I attach the process with gdb:

```
(gdb) info thread
  Id   Target Id         Frame 
* 1    Thread 0x7f85c554d400 (LWP 318513) "panda-system-x8" __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  2    Thread 0x7f85a3f02700 (LWP 318514) "panda-system-x8" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  3    Thread 0x7f859542b700 (LWP 318515) "panda-system-x8" 0x00007f85ba2e5936 in __deregister_frame_info_bases () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) thread 1
[Switching to thread 1 (Thread 0x7f85c554d400 (LWP 318513))]
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135	in ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S
(gdb) bt
#0  0x00007f85bfa381fd in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f85bfa31025 in __GI___pthread_mutex_lock (mutex=mutex@entry=0x563a1ccc0140 <qemu_global_mutex>) at ../nptl/pthread_mutex_lock.c:80
#2  0x0000563a1c139289 in qemu_mutex_lock (mutex=mutex@entry=0x563a1ccc0140 <qemu_global_mutex>) at /data/dataflowfastv2/uniformforward/panda/util/qemu-thread-posix.c:60
#3  0x0000563a1bdabc81 in qemu_mutex_lock_iothread () at /data/dataflowfastv2/uniformforward/panda/cpus.c:1459
#4  0x0000563a1c135c42 in os_host_main_loop_wait (timeout=<optimized out>) at /data/dataflowfastv2/uniformforward/panda/util/main-loop.c:262
#5  0x0000563a1c135c42 in main_loop_wait (nonblocking=<optimized out>) at /data/dataflowfastv2/uniformforward/panda/util/main-loop.c:531
#6  0x0000563a1beac8fa in main_loop () at /data/dataflowfastv2/uniformforward/panda/vl.c:1968
#7  0x0000563a1beb2259 in main_aux (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>, pmm=PANDA_NORMAL) at /data/dataflowfastv2/uniformforward/panda/vl.c:5065
#8  0x00007f85b9f03bf7 in __libc_start_main (main=0x563a1bd29500 <main>, argc=17, argv=0x7fffe1636428, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffe1636418) at ../csu/libc-start.c:310
#9  0x0000563a1bd2b94a in _start ()
(gdb) thread 2
[Switching to thread 2 (Thread 0x7f85a3f02700 (LWP 318514))]
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
(gdb) bt
#0  0x00007f85b9ffd639 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000563a1c139705 in qemu_futex_wait (val=<optimized out>, f=<optimized out>) at /data/dataflowfastv2/uniformforward/panda/include/qemu/futex.h:26
#2  0x0000563a1c139705 in qemu_event_wait (ev=ev@entry=0x563a1d105d64 <rcu_call_ready_event>) at /data/dataflowfastv2/uniformforward/panda/util/qemu-thread-posix.c:399
#3  0x0000563a1c14912e in call_rcu_thread (opaque=<optimized out>) at /data/dataflowfastv2/uniformforward/panda/util/rcu.c:249
#4  0x00007f85bfa2e6db in start_thread (arg=0x7f85a3f02700) at pthread_create.c:463
#5  0x00007f85ba00371f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) thread 3 
[Switching to thread 3 (Thread 0x7f859542b700 (LWP 318515))]
#0  0x00007f85ba2e5936 in __deregister_frame_info_bases () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt
#0  0x00007f85ba2e5936 in __deregister_frame_info_bases () at /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007f85ba2e5a29 in __deregister_frame () at /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007f85bc9e4f68 in llvm::RTDyldMemoryManager::deregisterEHFrames() () at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#3  0x00007f85bc9d9409 in llvm::orc::RTDyldObjectLinkingLayer::~RTDyldObjectLinkingLayer() () at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#4  0x00007f85bc9d94e9 in llvm::orc::RTDyldObjectLinkingLayer::~RTDyldObjectLinkingLayer() () at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#5  0x00007f85bc9b8afb in llvm::orc::LLJIT::~LLJIT() () at /usr/lib/x86_64-linux-gnu/libLLVM-10.so.1
#6  0x0000563a1bd65bc6 in llvm::orc::LLLazyJIT::~LLLazyJIT() (this=0x7f856c54a1c0, __in_chrg=<optimized out>) at /usr/lib/llvm-10/include/llvm/ExecutionEngine/Orc/LLJIT.h:154
#7  0x0000563a1bd65bc6 in std::default_delete<llvm::orc::LLLazyJIT>::operator()(llvm::orc::LLLazyJIT*) const (this=<optimized out>, __ptr=0x7f856c54a1c0) at /usr/include/c++/7/bits/unique_ptr.h:78
#8  0x0000563a1bd65bc6 in std::unique_ptr<llvm::orc::LLLazyJIT, std::default_delete<llvm::orc::LLLazyJIT> >::~unique_ptr() (this=0x7f856c544f90, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/unique_ptr.h:263
#9  0x0000563a1bd65bc6 in TCGLLVMTranslator::~TCGLLVMTranslator() (this=0x7f856c544d50, __in_chrg=<optimized out>) at /data/dataflowfastv2/uniformforward/panda/panda/llvm/tcg-llvm.cpp:1500
#10 0x0000563a1bd65e3e in tcg_llvm_destroy() () at /data/dataflowfastv2/uniformforward/panda/panda/llvm/tcg-llvm.cpp:1560
#11 0x0000563a1bd2cce8 in panda_disable_llvm () at /data/dataflowfastv2/uniformforward/panda/panda/src/callbacks.c:675
#12 0x00007f85a2806237 in uninit_plugin(void*) (self=<optimized out>) at /data/dataflowfastv2/uniformforward/panda/panda/plugins/taint2/taint2.cpp:565
#13 0x0000563a1bd2ca1a in panda_do_unload_plugin (plugin_idx=4) at /data/dataflowfastv2/uniformforward/panda/panda/src/callbacks.c:353
#14 0x0000563a1bd2cb18 in panda_unload_plugins () at /data/dataflowfastv2/uniformforward/panda/panda/src/callbacks.c:394
#15 0x0000563a1bd2fc39 in panda_cleanup () at /data/dataflowfastv2/uniformforward/panda/panda/src/common.c:199
#16 0x0000563a1bd3a21a in rr_do_end_replay (is_error=is_error@entry=0) at /data/dataflowfastv2/uniformforward/panda/panda/src/rr/rr_log.c:1659
#17 0x0000563a1bd8a3e4 in cpu_exec (cpu=cpu@entry=0x563a1ef23670) at /data/dataflowfastv2/uniformforward/panda/cpu-exec.c:857
#18 0x0000563a1bdabe40 in tcg_cpu_exec (cpu=0x563a1ef23670) at /data/dataflowfastv2/uniformforward/panda/cpus.c:1200
#19 0x0000563a1bdabe40 in qemu_tcg_cpu_thread_fn (arg=<optimized out>) at /data/dataflowfastv2/uniformforward/panda/cpus.c:1298
#20 0x00007f85bfa2e6db in start_thread (arg=0x7f859542b700) at pthread_create.c:463
#21 0x00007f85ba00371f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

It seems that `panda_disable_llvm` called by `uninit_plugin` is running  a infinit -loop.
Strange behaviour.
Is this a bug of panda-re or a bug of llvm ?

**Comment by bingosxs** [comment]
I also find that the process can terminate after debug detach.


```
(gdb) thread 2
[Switching to thread 2 (Thread 0x7fbca76b9700 (LWP 362465))]
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
(gdb) bt
#0  0x00007fbcbd7b4639 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005601c5455705 in qemu_futex_wait (val=<optimized out>, f=<optimized out>) at /data/dataflowfastv2/uniformforward/panda/include/qemu/futex.h:26
#2  0x00005601c5455705 in qemu_event_wait (ev=ev@entry=0x5601c6421d64 <rcu_call_ready_event>) at /data/dataflowfastv2/uniformforward/panda/util/qemu-thread-posix.c:399
#3  0x00005601c546512e in call_rcu_thread (opaque=<optimized out>) at /data/dataflowfastv2/uniformforward/panda/util/rcu.c:249
#4  0x00007fbcc31e56db in start_thread (arg=0x7fbca76b9700) at pthread_create.c:463
#5  0x00007fbcbd7ba71f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) quit
A debugging session is active.

	Inferior 1 [process 362464] will be detached.

Quit anyway? (y or n) y
Detaching from program: /data/dataflowfastv2/uniformforward/build/x86_64-softmmu/panda-system-x86_64, process 362464


```

**Comment by AndrewFasano** [comment]
Thanks for the bug report - it looks like that's probably a bug in PANDA. If you're still encountering this, we could try helping if you can share your replay files.
