### ISSUE TITLE
panda_install_bash.sh on 32bit Ubuntu 14.04: pycparser error

### ISSUE THREAD

**Issue by gitttt** [panda-re/panda#85]
I tried to install panda on my Ubuntu 14.04 32bit system. I used the "panda_install_bash" script as recommended.
The Installation went well up to the point where it said:

Building API for plugin taint
Traceback (most recent call last):
File "../scripts/apigen.py", line 198, in
generate_api(plugin, plugin_dir)
File "../scripts/apigen.py", line 164, in generate_api
arglist = get_arglists(pf)
File "../scripts/apigen.py", line 24, in get_arglists
p = pyc.parse(pf)
File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 146, in parse
debug=debuglevel)
File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 265, in parse
return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
tok = self.errorfunc(errtoken)
File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1680, in p_error
column=self.clex.find_tok_column(p)))
File "/usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py", line 55, in parse_error
raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/stdint.h:57:1: before: __extension_

In the /usr/include/stdint.h I have:

47 /\* Unsigned. */
48 typedef unsigned char uint8_t;
49 typedef unsigned short int uint16_t;
50 #ifndef uint32_t_defined
51 typedef unsigned int uint32_t;
52 # define __uint32_t_defined
53 #endif
54 #if __WORDSIZE == 64
55 typedef unsigned long int uint64_t;
56 #else
57 __extension
58 typedef unsigned long long int uint64_t;
59 #endif

Any idea what this error is about?
Thanks for any hints!

**Comment by windcarp** [comment]
I've also met with this problem :sob:

**Comment by supky** [comment]
Did someone have any idea to solve it ? I have installed all  prerequisites followed compile.md. And It don't have any problem or error. But when I was installing qemu of PANDA using ./build.sh command, there are something wrong that same as the questioner.
```
root@hc-virtual-machine:~/panda/qemu# ./build.sh 
Building API for plugin sample ... Done!
Building API for plugin taint
Traceback (most recent call last):
  File "../scripts/apigen.py", line 198, in <module>
    generate_api(plugin, plugin_dir)
  File "../scripts/apigen.py", line 164, in generate_api
    arglist = get_arglists(pf)
  File "../scripts/apigen.py", line 24, in get_arglists
    p = pyc.parse(pf)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 138, in parse
    debug=debuglevel)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python2.7/dist-packages/pycparser/c_parser.py", line 1613, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python2.7/dist-packages/pycparser/plyparser.py", line 54, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/stdint.h:57:1: before: __extension_
```

My system is  Ubuntu 14.04 32bit system, and the version of clang and llvm all is 3.3. At the begin, I think it may be the version of pycparser. But I have tried many version of pycparser, such as 2.14, 2.13，2.12， 2.11， 2.10， 2.09. However , they all didn't work.

```
root@hc-virtual-machine:~# clang --version
clang version 3.3 (tags/RELEASE_33/final ^/cfe/tags/RELEASE_33/final 274457)
Target: i386-pc-linux-gnu
Thread model: posix
root@hc-virtual-machine:~# 
```

```
root@hc-virtual-machine:~# g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This problem have bothered me for many days. Thank you for any answer provided by you !

**Comment by moyix** [comment]
We have only tested PANDA on 64-bit Linux. At the very least, the taint analysis requires a 64-bit address space for its shadow memory map. Could you try on 64-bit Ubuntu and see if that resolves the issue?

**Comment by supky** [comment]
I have tried it on my computer . It can work. So, don't use 32-bit systems as your PANDA environment .
