### ISSUE TITLE
Segfaults when recording ARM cortex-m3

### ISSUE THREAD

**Issue by shijiameng** [panda-re/panda#899]
I was trying to record the firmware of lm3s6965evb. It ended up with a segmentation fault when the command "end_record" was issued. Backtrace of the call stack was as follows:

```
(qemu) end_record
(qemu) Time taken was: 5 seconds.

Thread 1 "panda-system-ar" received signal SIGSEGV, Segmentation fault.
0x00007ffff795cb90 in crc32_z () from /lib/x86_64-linux-gnu/libz.so.1
(gdb) bt
#0  0x00007ffff795cb90 in crc32_z () at /lib/x86_64-linux-gnu/libz.so.1
#1  0x0000555555876c56 in  ()
#2  0x000055555587e112 in rr_do_end_record ()
#3  0x0000555555a223a7 in main_loop ()
#4  0x0000555555a27929 in main_aux ()
#5  0x00007fffecac9bf7 in __libc_start_main (main=
    0x55555586c610 <main>, argc=12, argv=0x7fffffffdf38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf28) at ../csu/libc-start.c:310
#6  0x000055555586f08a in _start ()
(gdb) 
```

This issue is quite similar to what mentioned in #525. I tried the solution (@bellma) however it doesn't work with ARM cortex-m3.

**Comment by shijiameng** [comment]
It seems that the memory size must be specified smaller than or equal to 256K when emulating lm3s6965evb board, otherwise PANDA would crash when ending the record.

e.g.  panda-system-arm -monitor stdio -kernel=firmware.elf **-m 256K** -cpu cortex-m3 -machine lm3s6965evb
