### ISSUE TITLE
PyPANDA ` proc_start_linux` work fine,  `hook_symbol` not working occasionally #901

### ISSUE THREAD

**Issue by fengjian** [panda-re/panda#933]
```python
from pandare import Panda, blocking
panda = Panda(generic="x86_64")


@panda.hook_symbol("libc", None, procname="uaf", name="hook_symbols")
def hook_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    print(f"{procname} {libname} {symname}")

@panda.ppp("proc_start_linux", "on_rec_auxv")
def rec_auxv(cpu, tb, auxv):
    procname = panda.get_process_name(cpu)
    print(f"got to proc_start_linux {procname}")


@blocking
def run_cmd():
    # First revert to root snapshot, then type a command via serial
    panda.revert_sync("root")
    panda.copy_to_guest("/home/target")
    print(panda.run_serial_cmd("uname -a"))
    print(panda.run_serial_cmd("cp /root/target/uaf /tmp/uaf && chmod +x /tmp/uaf"))
    print(panda.run_serial_cmd("/tmp/uaf"))
    print("Finding cat in cat's memory map:")
    maps = panda.run_serial_cmd("cat /proc/self/maps")
    for line in maps.split("\n"):
        if 'cat' in line:
            print(line)
    panda.end_analysis()

panda.queue_async(run_cmd)
panda.run()

```

not working

```
root@afb84e173efe:/home# python test.py
using generic x86_64
Loading libpanda from /usr/local/lib/python3.8/dist-packages/pandare/data
PANDA[core]:os_familyno=2 bits=64 os_details=ubuntu:4.15.0-72-generic-noaslr-nokaslr
[PYPANDA] Panda args: [/usr/local/lib/python3.8/dist-packages/pandare/data/x86_64-softmmu/libpanda-x86_64.so -L /usr/local/lib/python3.8/dist-packages/pandare/data/pc-bios /root/.panda/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2 -display none -m 1024 -serial unix:/tmp/pypanda_s1a1y5tz5,server,nowait -monitor unix:/tmp/pypanda_mnk0olqep,server,nowait]
PANDA[core]:loading required plugin hooks
PANDA[core]:initializing hooks
PANDA[core]:loading required plugin dynamic_symbols
PANDA[core]:initializing dynamic_symbols
PANDA[core]:loading required plugin osi
PANDA[core]:initializing osi
PANDA[core]:loading required plugin osi_linux
PANDA[core]:initializing osi_linux
PANDA[osi_linux]:W> kernelinfo bytes [20-23] not read
PANDA[core]:loading required plugin syscalls2
PANDA[core]:initializing syscalls2
PANDA[syscalls2]:using profile for linux x64 64-bit
PANDA[core]:loading required plugin proc_start_linux
PANDA[core]:initializing proc_start_linux
PANDA[core]:loading required plugin syscalls2
PANDA[core]:/usr/local/lib/python3.8/dist-packages/pandare/data//x86_64-softmmu/panda/plugins//panda_syscalls2.so already loaded

PPP automatically loaded plugin proc_start_linux
PANDA[core]:loading required plugin proc_start_linux
PANDA[core]:/usr/local/lib/python3.8/dist-packages/pandare/data//x86_64-softmmu/panda/plugins//panda_proc_start_linux.so already loaded
[PYPANDA] Creating ISO /home/target.iso...
[PYPANDA] setup_sh = [mkdir -p target; while ! mount /dev/cdrom target; do sleep 0.3;  umount /dev/cdrom; done; target/setup.sh &> /dev/null || true ]
PANDA[core]:loading required plugin osi
PANDA[core]:/usr/local/lib/python3.8/dist-packages/pandare/data//x86_64-softmmu/panda/plugins//panda_osi.so already loaded
got to proc_start_linux mkdir
got to proc_start_linux mount
got to proc_start_linux cdrom_id
got to proc_start_linux cdrom_id
got to proc_start_linux ata_id
got to proc_start_linux umount
got to proc_start_linux sh
got to proc_start_linux ln
got to proc_start_linux readlink
[PYPANDA] mount: /root/target: wrong fs type, bad option, bad superblock on /dev/sr0, missing codepage or helper program, or other error.
umount: /dev/cdrom: not mounted.
mount: /root/target: WARNING: device write-protected, mounted read-only.
got to proc_start_linux cdrom_id
Linux ubuntu 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
got to proc_start_linux cp
got to proc_start_linux ata_id
got to proc_start_linux chmod

got to proc_start_linux uaf
got to proc_start_linux sh
got to proc_start_linux ln
got to proc_start_linux readlink
p1 malloc addr: 0x555555756260
hello world
free p1: hello world again
p2 malloc addr: 0x555555756260
p1 origin addr: 0x555555756260
call p1: whoami
root
Finding cat in cat's memory map:
got to proc_start_linux cat
555555554000-55555555c000 r-xp 00000000 08:01 19                         /bin/cat
55555575b000-55555575c000 r--p 00007000 08:01 19                         /bin/cat
55555575c000-55555575d000 rw-p 00008000 08:01 19                         /bin/cat
```

work fine

```
uaf libc-2.27.so _IO_do_write
uaf libc-2.27.so _IO_puts
uaf libc-2.27.so _IO_file_xsputn
uaf libc-2.27.so __overflow
uaf libc-2.27.so _IO_file_overflow
uaf libc-2.27.so _IO_do_write
uaf libc-2.27.so __libc_system
uaf libc-2.27.so sigaction
uaf libc-2.27.so sigaction
uaf libc-2.27.so sigprocmask
uaf libc-2.27.so waitpid
got to proc_start_linux sh
got to proc_start_linux whoami
got to proc_start_linux cdrom_id
uaf libc-2.27.so sigaction
uaf libc-2.27.so sigaction
uaf libc-2.27.so sigprocmask
uaf libc-2.27.so _IO_file_setbuf
p1 malloc addr: 0x555555756260
hello world
free p1: hello world again
p2 malloc addr: 0x555555756260
p1 origin addr: 0x555555756260
call p1: whoami
root
Finding cat in cat's memory map:
got to proc_start_linux cat
got to proc_start_linux ata_id
555555554000-55555555c000 r-xp 00000000 08:01 19                         /bin/cat
55555575b000-55555575c000 r--p 00007000 08:01 19                         /bin/cat
55555575c000-55555575d000 rw-p 00008000 08:01 19                         /bin/cat
```

test 2
```python
from pandare import Panda, blocking
panda = Panda(generic="x86_64")


@panda.hook_symbol("libc", None, procname="cat", name="hook_symbols")
def hook_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    print(f"{procname} {libname} {symname}")

@panda.ppp("proc_start_linux", "on_rec_auxv")
def rec_auxv(cpu, tb, auxv):
    procname = panda.get_process_name(cpu)
    print(f"got to proc_start_linux {procname}")


@blocking
def run_cmd():
    # First revert to root snapshot, then type a command via serial
    panda.revert_sync("root")
    panda.copy_to_guest("/home/target")
    print(panda.run_serial_cmd("uname -a"))
    print(panda.run_serial_cmd("cp /root/target/uaf /tmp/uaf && chmod +x /tmp/uaf"))
    print(panda.run_serial_cmd("/tmp/uaf"))
    print("Finding cat in cat's memory map:")
    maps = panda.run_serial_cmd("cat /proc/self/maps")
    for line in maps.split("\n"):
        if 'cat' in line:
            print(line)
    panda.end_analysis()

panda.queue_async(run_cmd)
panda.run()
```

not working
```
[PYPANDA] mount: /root/target: WARNING: device write-protected, mounted read-only.
got to proc_start_linux uname
Linux ubuntu 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
got to proc_start_linux cp
got to proc_start_linux sh
got to proc_start_linux ln
got to proc_start_linux ln
got to proc_start_linux readlink

got to proc_start_linux uaf
got to proc_start_linux sh
got to proc_start_linux cdrom_id
p1 malloc addr: 0x555555756260
hello world
free p1: hello world again
p2 malloc addr: 0x555555756260
p1 origin addr: 0x555555756260
call p1: whoami
root
Finding cat in cat's memory map:
got to proc_start_linux cat
got to proc_start_linux ata_id
555555554000-55555555c000 r-xp 00000000 08:01 19                         /bin/cat
55555575b000-55555575c000 r--p 00007000 08:01 19                         /bin/cat
55555575c000-55555575d000 rw-p 00008000 08:01 19                         /bin/cat
```

test3  comment copy_to_guest code
```python
from pandare import Panda, blocking
panda = Panda(generic="x86_64")


@panda.hook_symbol("libc", None, procname="cat", name="hook_symbols")
def hook_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    print(f"{procname} {libname} {symname}")

@panda.ppp("proc_start_linux", "on_rec_auxv")
def rec_auxv(cpu, tb, auxv):
    procname = panda.get_process_name(cpu)
    print(f"got to proc_start_linux {procname}")


@blocking
def run_cmd():
    # First revert to root snapshot, then type a command via serial
    panda.revert_sync("root")
    #panda.copy_to_guest("/home/target")
    print(panda.run_serial_cmd("uname -a"))
    #print(panda.run_serial_cmd("cp /root/target/uaf /tmp/uaf && chmod +x /tmp/uaf"))
    #print(panda.run_serial_cmd("/tmp/uaf"))
    print("Finding cat in cat's memory map:")
    maps = panda.run_serial_cmd("cat /proc/self/maps")
    for line in maps.split("\n"):
        if 'cat' in line:
            print(line)
    panda.end_analysis()

panda.queue_async(run_cmd)
panda.run()
```

work fine

```
cat libc-2.27.so _IO_file_close_it
cat libc-2.27.so _IO_unsave_markers
cat libc-2.27.so _IO_file_close
cat libc-2.27.so __close_nocancel
cat libc-2.27.so _IO_setb
cat libc-2.27.so _IO_un_link
cat libc-2.27.so _IO_file_finish
cat libc-2.27.so _IO_default_finish
cat libc-2.27.so __cxa_finalize
cat libc-2.27.so _exit
555555554000-55555555c000 r-xp 00000000 08:01 19                         /bin/cat
55555575b000-55555575c000 r--p 00007000 08:01 19                         /bin/cat
55555575c000-55555575d000 rw-p 00008000 08:01 19                         /bin/cat
```

test4

```python
from pandare import Panda, blocking
panda = Panda(generic="x86_64")


@panda.hook_symbol("libc", "malloc") 
def hook_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    print(f"{procname} {libname} {symname}")

@panda.ppp("proc_start_linux", "on_rec_auxv")
def rec_auxv(cpu, tb, auxv):
    procname = panda.get_process_name(cpu)
    print(f"got to proc_start_linux {procname}")


@blocking
def run_cmd():
    # First revert to root snapshot, then type a command via serial
    panda.revert_sync("root")
    #panda.copy_to_guest("/home/target")
    print(panda.run_serial_cmd("uname -a"))
    #print(panda.run_serial_cmd("cp /root/target/uaf /tmp/uaf && chmod +x /tmp/uaf"))
    #print(panda.run_serial_cmd("/tmp/uaf"))
    print("Finding cat in cat's memory map:")
    maps = panda.run_serial_cmd("cat /proc/self/maps")
    for line in maps.split("\n"):
        if 'cat' in line:
            print(line)
    panda.end_analysis()

panda.queue_async(run_cmd)
panda.run()
```
The cat has malloc

```
cat libc-2.27.so malloc
cat libc-2.27.so malloc
cat libc-2.27.so malloc
cat libc-2.27.so malloc
cat libc-2.27.so malloc
bash libc-2.27.so malloc
bash libc-2.27.so malloc
bash libc-2.27.so malloc
bash libc-2.27.so malloc
bash libc-2.27.so malloc
```

when procname is not None,  not working occasionally

```python
@panda.hook_symbol("libc", "malloc", procname="cat", name="hook_symbols")
def hook_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
```

```
PANDA[core]:/usr/local/lib/python3.8/dist-packages/pandare/data//x86_64-softmmu/panda/plugins//panda_osi.so already loaded
got to proc_start_linux uname
Linux ubuntu 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Finding cat in cat's memory map:
got to proc_start_linux cat
555555554000-55555555c000 r-xp 00000000 08:01 19                         /bin/cat
55555575b000-55555575c000 r--p 00007000 08:01 19                         /bin/cat
55555575c000-55555575d000 rw-p 00008000 08:01 19                         /bin/cat
```

**Comment by lacraig2** [comment]
PR #950 should fix this. Let me know if it does.

**Comment by fengjian** [comment]
> PR #950 should fix this. Let me know if it does.

> PR #950 should fix this. Let me know if it does.

I've tried the PR #950 and lastest image 

work fine

```python
from pandare import Panda, blocking
import os.path

panda = Panda(generic="x86_64")


@panda.hook_symbol("libc", "cfree", procname="uaf", name="hook_cfree_symbols")
def hook_cfree_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    if procname == "uaf":
        print(f"{procname} {libname} {symname}")

@panda.hook_symbol("libc", "__libc_malloc", procname="uaf", name="hook_malloc_symbols")
def hook_malloc_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    if procname == "uaf":
        print(f"{procname} {libname} {symname}")



@blocking
def run_cmd():
    # First revert to root snapshot, then type a command via serial

    panda.revert_sync("root")
    panda.copy_to_guest("/root/.panda/target")
    print(panda.run_serial_cmd("uname -a"))
    print(panda.run_serial_cmd("cp /root/target/uaf /tmp/uaf && chmod +x /tmp/uaf"))
    print(panda.run_serial_cmd("/tmp/uaf"))
    print("Finding cat in cat's memory map:")
    maps = panda.run_serial_cmd("cat /proc/self/maps")
    for line in maps.split("\n"):
        if 'cat' in line:
            print(line)
    panda.end_analysis()


panda.queue_async(run_cmd)
panda.run()
```

```
[PYPANDA] mount: /root/target: WARNING: device write-protected, mounted read-only.
Linux ubuntu 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

PANDA[core]:loading required plugin osi
PANDA[core]:/panda/build//x86_64-softmmu/panda/plugins//panda_osi.so already loaded
uaf libc-2.27.so __libc_malloc
uaf libc-2.27.so __libc_malloc
uaf libc-2.27.so cfree
uaf libc-2.27.so __libc_malloc
p1 malloc addr: 0x555555756260
hello world
free p1: hello world again
p2 malloc addr: 0x555555756260
p1 origin addr: 0x555555756260
call p1: whoami
root
```


some error calls has occurred  and pandare.panda_expect timeout


```python
from pandare import Panda, blocking
import os.path

panda = Panda(generic="x86_64")


@panda.hook_symbol("libc", None, procname="uaf", name="hook_cfree_symbols")
def hook_cfree_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    if procname == "uaf":
        print(f"{procname} {libname} {symname}")

@panda.hook_symbol("libc", "__libc_malloc", procname="uaf", name="hook_malloc_symbols")
def hook_malloc_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    if procname == "uaf":
        print(f"{procname} {libname} {symname}")



@blocking
def run_cmd():
    # First revert to root snapshot, then type a command via serial

    panda.revert_sync("root")
    panda.copy_to_guest("/root/.panda/target")
    print(panda.run_serial_cmd("uname -a"))
    print(panda.run_serial_cmd("cp /root/target/uaf /tmp/uaf && chmod +x /tmp/uaf"))
    print(panda.run_serial_cmd("/tmp/uaf"))
    print("Finding cat in cat's memory map:")
    maps = panda.run_serial_cmd("cat /proc/self/maps")
    for line in maps.split("\n"):
        if 'cat' in line:
            print(line)
    panda.end_analysis()


panda.queue_async(run_cmd)
panda.run()
```

```
uaf libc-2.27.so _IO_file_xsputn
uaf libc-2.27.so _IO_file_overflow
uaf libc-2.27.so _IO_do_write
uaf libc-2.27.so _IO_file_write
uaf libc-2.27.so __write
uaf libc-2.27.so puts
uaf libc-2.27.so _IO_file_xsputn
uaf libc-2.27.so __overflow
uaf libc-2.27.so _IO_file_overflow
uaf libc-2.27.so _IO_do_write
uaf libc-2.27.so _IO_file_write
uaf libc-2.27.so __write
uaf libc-2.27.so __libc_system
uaf libc-2.27.so sigaction
uaf libc-2.27.so sigaction
uaf libc-2.27.so sigprocmask
uaf libc-2.27.so waitpid
uaf libc-2.27.so sigaction
uaf libc-2.27.so sigaction
uaf libc-2.27.so sigprocmask
uaf libc-2.27.so execve
Traceback (most recent call last):
  File "test2.py", line 43, in <module>
    panda.run()
  File "/panda/panda/python/core/pandare/panda.py", line 469, in run
    raise saved_exception
  File "/panda/panda/python/core/pandare/panda.py", line 865, in wrapper
    f()
  File "/panda/panda/python/core/pandare/utils.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "test2.py", line 33, in run_cmd
    print(panda.run_serial_cmd("/tmp/uaf"))
  File "/panda/panda/python/core/pandare/utils.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/panda/panda/python/core/pandare/panda.py", line 2003, in run_serial_cmd
    result = self.serial_console.expect(timeout=timeout)
  File "/panda/panda/python/core/pandare/panda_expect.py", line 423, in expect
    raise TimeoutExpired(f"{self.name} Read message \n{full_buffer}\n")
pandare.panda_expect.TimeoutExpired: serial Read message
['/tmp/uaf', 'p1 malloc addr: 0x555555756260', 'hello world', 'free p1: hello world again', 'p2 malloc addr: 0x555555756260', 'p1 origin addr: 0x555555756260', 'call p1: whoami', bytearray(b'r')]

```

**Comment by fengjian** [comment]
procname filter not working occasionally

```
from pandare import Panda, blocking
import os.path

panda = Panda(generic="x86_64")


@panda.hook_symbol("libc", "printf", procname="uaf", name="hook_cfree_symbols")
def hook_cfree_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    print(f"{procname} {libname} {symname}")

@panda.hook_symbol("libc", "__libc_malloc", procname="uaf", name="hook_malloc_symbols")
def hook_malloc_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    print(f"{procname} {libname} {symname}")



@blocking
def run_cmd():
    # First revert to root snapshot, then type a command via serial

    panda.revert_sync("root")
    panda.copy_to_guest("/root/.panda/target")
    print(panda.run_serial_cmd("uname -a"))
    print(panda.run_serial_cmd("cp /root/target/uaf /tmp/uaf && chmod +x /tmp/uaf"))
    print(panda.run_serial_cmd("/tmp/uaf"))
    print("Finding cat in cat's memory map:")
    maps = panda.run_serial_cmd("cat /proc/self/maps")
    for line in maps.split("\n"):
        if 'cat' in line:
            print(line)
    panda.end_analysis()


panda.queue_async(run_cmd)
panda.run()
```


```
Linux ubuntu 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

PANDA[core]:loading required plugin osi
PANDA[core]:/panda/build//x86_64-softmmu/panda/plugins//panda_osi.so already loaded
uaf libc-2.27.so __libc_malloc
uaf libc-2.27.so printf
uaf libc-2.27.so __libc_malloc
uaf libc-2.27.so __libc_malloc
uaf libc-2.27.so printf
uaf libc-2.27.so printf
(spawn) libc-2.27.so __libc_malloc
p1 malloc addr: 0x555555756260
hello world
free p1: hello world again
p2 malloc addr: 0x555555756260
p1 origin addr: 0x555555756260
call p1: whoami
root
Finding cat in cat's memory map:
ata_id libc-2.27.so __libc_malloc
ata_id libc-2.27.so __libc_malloc
ata_id libc-2.27.so __libc_malloc
```

**Comment by lacraig2** [comment]
So RE the first issue it seems to be a timeout issue. There's a setting to turn off the timeout or set it to a longer value than the default of 30. See: https://panda-re.github.io/panda.html#pandare.panda.Panda.run_serial_cmd

The way we currently handle process transitions is checking for `sys_exit`. If your program doesn't call it (because it errored out) we don't have that case handled quite yet.

**Comment by fengjian** [comment]
> So RE the first issue it seems to be a timeout issue. There's a setting to turn off the timeout or set it to a longer value than the default of 30. See: https://panda-re.github.io/panda.html#pandare.panda.Panda.run_serial_cmd
> 
> The way we currently handle process transitions is checking for `sys_exit`. If your program doesn't call it (because it errored out) we don't have that case handled quite yet.

uaf has sys_exit_group 


```
strace ./uaf
execve("./uaf", ["./uaf"], 0x7ffde3739630 /* 21 vars */) = 0
brk(NULL)                               = 0x55b689c59000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=59835, ...}) = 0
mmap(NULL, 59835, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fa85674b000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\34\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2030544, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa856749000
mmap(NULL, 4131552, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa856142000
mprotect(0x7fa856329000, 2097152, PROT_NONE) = 0
mmap(0x7fa856529000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e7000) = 0x7fa856529000
mmap(0x7fa85652f000, 15072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fa85652f000
close(3)                                = 0
arch_prctl(ARCH_SET_FS, 0x7fa85674a4c0) = 0
mprotect(0x7fa856529000, 16384, PROT_READ) = 0
mprotect(0x55b688523000, 4096, PROT_READ) = 0
mprotect(0x7fa85675a000, 4096, PROT_READ) = 0
munmap(0x7fa85674b000, 59835)           = 0
brk(NULL)                               = 0x55b689c59000
brk(0x55b689c7a000)                     = 0x55b689c7a000
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 5), ...}) = 0
write(1, "p1 malloc addr: 0x55b689c59260\n", 31p1 malloc addr: 0x55b689c59260
) = 31
write(1, "hello world\n", 12hello world
)           = 12
write(1, "free p1: hello world again\n", 27free p1: hello world again
) = 27
write(1, "p2 malloc addr: 0x55b689c59260\n", 31p2 malloc addr: 0x55b689c59260
) = 31
write(1, "p1 origin addr: 0x55b689c59260\n", 31p1 origin addr: 0x55b689c59260
) = 31
write(1, "call p1: whoami\n", 16call p1: whoami
)       = 16
rt_sigaction(SIGINT, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fa856180fd0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fa856180fd0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
clone(child_stack=NULL, flags=CLONE_PARENT_SETTID|SIGCHLD, parent_tidptr=0x7fff4ec2edac) = 18107
wait4(18107, root
[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 18107
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fa856180fd0}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fa856180fd0}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=18107, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by fengjian** [comment]
> So RE the first issue it seems to be a timeout issue. There's a setting to turn off the timeout or set it to a longer value than the default of 30. See: https://panda-re.github.io/panda.html#pandare.panda.Panda.run_serial_cmd
> 
> The way we currently handle process transitions is checking for `sys_exit`. If your program doesn't call it (because it errored out) we don't have that case handled quite yet.

**Comment by fengjian** [comment]
> So RE the first issue it seems to be a timeout issue. There's a setting to turn off the timeout or set it to a longer value than the default of 30. See: https://panda-re.github.io/panda.html#pandare.panda.Panda.run_serial_cmd
> 
> The way we currently handle process transitions is checking for `sys_exit`. If your program doesn't call it (because it errored out) we don't have that case handled quite yet.

we need checking for sys_exit and sys_exit_group?

```python
from pandare import Panda, blocking
import os.path

panda = Panda(generic="x86_64")


@panda.hook_symbol("libc", "cfree", procname="uaf", name="hook_cfree_symbols")
def hook_cfree_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    print(f"{procname} {libname} {symname}")

@panda.hook_symbol("libc", "__libc_malloc", procname="uaf", name="hook_malloc_symbols")
def hook_malloc_symbols(cpu, tb, h):
    procname = panda.get_process_name(cpu)
    libname = panda.ffi.string(h.sym.section).decode("utf-8", 'ignore')
    symname = panda.ffi.string(h.sym.name).decode("utf-8", 'ignore')
    print(f"{procname} {libname} {symname}")

@panda.ppp("syscalls2", "on_sys_exit_enter")
def on_sys_exit_enter(cpu, pc, code):
    if panda.in_kernel(cpu):
        return
    try:
        procname = panda.get_process_name(cpu)
        if procname == "uaf":
            print(f"[hook] proc:{procname} sys_exit_enter: {code}")
    except ValueError:
        return

@panda.ppp("syscalls2", "on_sys_exit_group_enter")
def on_sys_exit_group_enter(cpu, pc, code):
    if panda.in_kernel(cpu):
        return
    try:
        procname = panda.get_process_name(cpu)
        if procname == "uaf":
            print(f"[hook] proc:{procname} sys_exit_group_enter: {code}")
    except ValueError:
        return

@blocking
def run_cmd():
    # First revert to root snapshot, then type a command via serial

    panda.revert_sync("root")
    panda.copy_to_guest("/root/.panda/target")
    print(panda.run_serial_cmd("uname -a"))
    print(panda.run_serial_cmd("cp /root/target/uaf /tmp/uaf && chmod +x /tmp/uaf"))
    print(panda.run_serial_cmd("/tmp/uaf"))
    print("Finding cat in cat's memory map:")
    maps = panda.run_serial_cmd("cat /proc/self/maps")
    for line in maps.split("\n"):
        if 'cat' in line:
            print(line)
    panda.end_analysis()


panda.queue_async(run_cmd)
panda.run()
```

```
(spawn) libc-2.27.so cfree
(spawn) libc-2.27.so cfree
(spawn) libc-2.27.so cfree
(spawn) libc-2.27.so cfree
(spawn) libc-2.27.so cfree
(spawn) libc-2.27.so cfree
(spawn) libc-2.27.so cfree
[hook] proc:uaf sys_exit_group_enter: 0
p1 malloc addr: 0x555555756260
hello world
free p1: hello world again
p2 malloc addr: 0x555555756260
p1 origin addr: 0x555555756260
call p1: whoami
root
Finding cat in cat's memory map:
555555554000-55555555c000 r-xp 00000000 08:01 19                         /bin/cat
55555575b000-55555575c000 r--p 00007000 08:01 19                         /bin/cat
55555575c000-55555575d000 rw-p 00008000 08:01 19                         /bin/cat

```

**Comment by lacraig2** [comment]
Hi @fengjian,

You've brought up some good points here. I've issued PR #958 to address them.

They drop support for filtering by process name. The functionality is really just better handled by users and as you mentioned the functionality around spawning processes and forking can get very complicated. To avoid bloat this is best left to the users.

For efficiency though it's worth mentioning that the following structure will work quite well:
```Python
@panda.hook_symbol("libc-","system")
def hook(cpu,tb,h):
    if program_name in panda.get_process_name(cpu):
        # do things
	else:
		# you can disable the hook here because
		# a new hook is spawned for each ASID
		# so at MAX you deal with each new process
		# one time.
		h.enabled = False
```

Let me know if the new changes work for you. Thanks.
