### ISSUE TITLE
PyPANDA hanged on pandare.panda_expect  if  `panda.enable_llvm()`

### ISSUE THREAD

**Issue by fengjian** [panda-re/panda#940]
cpu: intel E5 x86_64 x2
host: ubuntu18.04
panda_version: docker pull pandare/panda
image: bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2

```python
from pandare import Panda, blocking
panda = Panda(generic="x86_64")

panda.enable_llvm()

libc = {
        "__libc_malloc": 0x97070,
         "malloc": 0x97070,
        "__libc_free": 0x97950,
        "cfree": 0x97950,
        "free": 0x97950
        }


shared_lib_addr_space = 0x7ffff0000000
libc_baseaddr = 0x7ffff79e4000

malloc_count = 0
@panda.hook2_single_insn("malloc_hook", libc["malloc"]+libc_baseaddr, procname="uaf",)#libname="libc")
def malloc_hook(cpu, tb, h):
    global malloc_count
    procname = panda.get_process_name(cpu)
    sp = panda.current_sp(cpu)
    retaddr = panda.arch.get_return_address(cpu)
    size = panda.arch.get_arg(cpu, 0)


    print(f"malloc hook: {procname} {retaddr:x} arg0: {size}")
    if retaddr < shared_lib_addr_space:
        malloc_count += 1
    return True

free_count = 0
@panda.hook2_single_insn("free_hook", libc["free"]+libc_baseaddr, procname="uaf",)# libname="libc")
def free_hook(cpu, tb, h):
    global free_count
    procname = panda.get_process_name(cpu)
    sp = panda.current_sp(cpu)
    retaddr = panda.arch.get_return_address(cpu)
    addr = panda.arch.get_arg(cpu, 0)

    print(f"free hook: {procname} {retaddr:x} arg0: {addr:x}")
    if retaddr < shared_lib_addr_space:
        free_count += 1
    return True

@blocking
def run_cmd():
    # First revert to root snapshot, then type a command via serial
    panda.revert_sync("root")
    panda.copy_to_guest("/root/.panda/target")
    print(panda.run_serial_cmd("uname -a"))
    print(panda.run_serial_cmd("cp /root/target/uaf /tmp/uaf && chmod +x /tmp/uaf"))
    print(panda.run_serial_cmd("/tmp/uaf"))
    print("Finding cat in cat's memory map:")
    maps = panda.run_serial_cmd("cat /proc/self/maps")
    for line in maps.split("\n"):
        if 'cat' in line:
            print(line)
    panda.end_analysis()

panda.queue_async(run_cmd)
panda.run()

print(malloc_count)
print(free_count)
```

```
[PYPANDA] Creating ISO /root/.panda/target.iso...
[PYPANDA] setup_sh = [mkdir -p target; while ! mount /dev/cdrom target; do sleep 0.3;  umount /dev/cdrom; done; target/setup.sh &> /dev/null || true ]
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    panda.run()
  File "/usr/local/lib/python3.8/dist-packages/pandare/panda.py", line 455, in run
    raise saved_exception
  File "/usr/local/lib/python3.8/dist-packages/pandare/panda.py", line 827, in wrapper
    f()
  File "/usr/local/lib/python3.8/dist-packages/pandare/utils.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "test.py", line 62, in run_cmd
    panda.copy_to_guest("/root/.panda/target")
  File "/usr/local/lib/python3.8/dist-packages/pandare/utils.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandare/panda.py", line 2012, in copy_to_guest
    progress(self.run_serial_cmd(setup_sh))
  File "/usr/local/lib/python3.8/dist-packages/pandare/utils.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandare/panda.py", line 1948, in run_serial_cmd
    result = self.serial_console.expect(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pandare/panda_expect.py", line 353, in expect
    raise TimeoutExpired(f"{self.name} Read message \n{self.sofar}\n")
pandare.panda_expect.TimeoutExpired: serial Read message


```

**Comment by AndrewFasano** [comment]
I think what's going on here is that when running with LLVM there's some additional overhead and that's making the panda_expect timeout trigger even though the guest isn't totally hung.

I think a fix could be to expand panda.copy_to_guest to take a timeout parameter which it could then pass to panda.run_serial_cmd. Then in your call to copy_to_guest you could set a longer timeout.

Alternatively, you might be able to just move the `panda.enable_llvm()` call to after your `panda.copy_to_guest` call. That way you'll copy the files quickly and only enable LLVM for your actual analysis. I'm not positive that will work though
