### ISSUE TITLE
Syscalls2 broken for aarch64 after TCG changes

### ISSUE THREAD

**Issue by AndrewFasano** [panda-re/panda#980]
On commit: 59ab9cae39e22305d603583c0fded96b19d147d8

```py
from pandare import Panda
panda = Panda(generic="aarch64")

panda.load_plugin("syscalls2")

@panda.queue_blocking
def driver():
    panda.revert_sync("root")

panda.run()
```

Segfaults with a tcg error

```
Thread 6 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbb0a1700 (LWP 629324)]
0x00007ffff51fd455 in tcg_op_insert_after (s=0x7ffff5fd8880 <tcg_ctx>, old_op=0x0, opc=opc@entry=INDEX_op_movi_i64, nargs=nargs@entry=2) at /home/andrew/git/panda/tcg/tcg.c:1354
1354        int next = old_op->next;
(gdb) bt
#0  0x00007ffff51fd455 in tcg_op_insert_after (s=0x7ffff5fd8880 <tcg_ctx>, old_op=0x0, opc=opc@entry=INDEX_op_movi_i64, nargs=nargs@entry=2) at /home/andrew/git/panda/tcg/tcg.c:1354
#1  0x00007fffe2a00075 in insert_tcg_tmp<CPUState>(TCGOp**, CPUState*) (value=0xed2e10, after_op=0x7fffbb0a0d20) at /home/andrew/git/panda/tcg/tcg.h:825
#2  insert_args<CPUState*>(TCGOp**, CPUState*) (arg=0xed2e10, after_op=0x7fffbb0a0d20) at /home/andrew/git/panda/panda/include/panda/tcg-utils.h:49
#3  insert_args<CPUState*, TranslationBlock*, unsigned long>(TCGOp**, CPUState*, TranslationBlock*, unsigned long) (after_op=after_op@entry=0x7fffbb0a0d20, arg=arg@entry=0xed2e10)
    at /home/andrew/git/panda/panda/include/panda/tcg-utils.h:60
#4  0x00007fffe2a001cd in insert_call<void (CPUState*, TranslationBlock*, unsigned long), CPUState*, TranslationBlock*, unsigned long>(TCGOp**, void (*)(CPUState*, TranslationBlock*, unsigned long), CPUState*, TranslationBlock*, unsigned long) (after_op=after_op@entry=0x7fffbb0a0d20, func_ptr=func_ptr@entry=0x7fffe29cd9f0 <exec_callback(CPUState*, TranslationBlock*, unsigned long)>)
    at /home/andrew/git/panda/panda/include/panda/tcg-utils.h:82
#5  0x00007fffe29ff9e4 in before_tcg_codegen(CPUState*, TranslationBlock*) (cpu=0xed2e10, tb=0x7fffbb1d0dd0) at /home/andrew/git/panda/panda/plugins/syscalls2/syscalls2.cpp:945
#6  0x00007ffff519159f in panda_callbacks_before_tcg_codegen (cpu=0xed2e10, tb=tb@entry=0x7fffbb1d0dd0) at /home/andrew/git/panda/panda/src/cb-support.c:46
#7  0x00007ffff51f4bf7 in tb_gen_code (cpu=cpu@entry=0xed2e10, pc=281473497688388, cs_base=<optimized out>, flags=<optimized out>, cflags=<optimized out>, cflags@entry=0)
    at /home/andrew/git/panda/translate-all.c:1379
#8  0x00007ffff51f8be2 in tb_find (tb_exit=0, last_tb=<optimized out>, cpu=0xed2e10) at /home/andrew/git/panda/cpu-exec.c:427
#9  cpu_exec (cpu=cpu@entry=0xed2e10) at /home/andrew/git/panda/cpu-exec.c:831
#10 0x00007ffff521b533 in tcg_cpu_exec (cpu=0xed2e10) at /home/andrew/git/panda/cpus.c:1200
#11 qemu_tcg_cpu_thread_fn (arg=<optimized out>) at /home/andrew/git/panda/cpus.c:1298
#12 0x00007ffff7dad609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#13 0x00007ffff7ee9293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by AndrewFasano** [comment]
This bug isn't present prior to the recent TCG changes - I tried 6d0b06200a655d1a929cfc74c96a76a3138c2a34 and that works

**Comment by lacraig2** [comment]
It's not a TCG bug. It's a "we're giving the TCG ops trash" issue.

aarch64 syscalls2 was happening around the same time as syscalls2 updates. And we didn't merge things in correctly for that one case.

See #982. Easy fix.

**Comment by AndrewFasano** [comment]
Ah, that makes sense. Thanks for fixing, sorry I didn't figure it out on my own
